### ISSUE TITLE
Ideias pro futuro (roadmap)

### ISSUE THREAD

**Issue by filiagees** [KekkaiSensen/Tetris#1]
@KekkaiSensen , olhei o tetris, ainda tem bastante coisinhas pra fazer né. 
Então, ¿o que você acha do seguinte:
 - a gente quebrar o problema em várias partes pequenas, cada uma com sua própria função
 - eu escrevo um test-case para a função, e depois você escreve o código dela, para que o test passe a rodar OK
 - aí a gente usa ela no código, e o tetris fica um pouco mais próximo de ficar completo :muscle: 

Ou seja, isso seria parecido com desenvolvimento usando a metodologia _[Test Driven Development](https://bit.ly/wikiTDD)_ né? 

Se você topar, aí para cada parte/função eu crio uma issue igual a essa, e escrevo a ideia que eu pensei. Se você tiver uma ideia diferente, a gente conversa nela, até chegar num acordo e aí implementa ela.
**O que você acha?**.

----

Tipo, só para dar um exemplo, os próximos passos seriam algo como:
 - não deixar que o bloquinho "atravesse a parece", ao ir muito para os lados
 - os bloquinhos eles caírem automaticamente
 - eles se acumularem no fundo, empilhando-se
 - sumir com a linha depois de estar inteira preenchida

**Comment by KekkaiSensen** [comment]
@filiagees É uma ideia interessante

**Comment by KekkaiSensen** [comment]
Aliás, teria que criar mais variáveis para definir as bordas ? Já que vão ter diferentes formatos de blocos

**Comment by mar-moraes** [comment]
@filiagees É uma ideia interessante. Aliás, teria que criar mais variáveis para definir as bordas ? Já que vão ter diferentes formatos de blocos

**Comment by filiagees** [comment]
beleza :+1: 
então vou fechar essa issue e criar outras
